language: python
sudo: required
dist: trustyÏ
os:
  - osx
  - linux
addons:
  apt:
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - libgtk2.0-0
      - libx11-dev
      - libxkbfile-dev    
      - libsecret-1-dev
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
install:
  - npm install
  - npm run vscode:prepublish
  
script:
  - npm test --silent